### ISSUE TITLE
Can not find main.js or main.ts

### ISSUE THREAD

**Issue by samuil4** [kreuzerk/svg-icon-library-starter#3]
Hi when trying to start the project after `npm install` with `npm run serve` I get an error that there is no entry file `main.js ` for the webpack configuration in the directory `showcase`. 
I see that you have deleted that file, can you tell me why and how to run the showcase ?

Thanks :)

**Comment by nivekcode** [comment]
Hi @samuil4 I did a bigger rewrite of the starter in the last couple of days. Are you using the latest version?

**Comment by samuil4** [comment]
@kreuzerk yes, today checked out the latest version

**Comment by nivekcode** [comment]
Hi, @samuil4 you are right. Sorry, this was a mistake during the commit. I added the file back. Thx a lot for bringing this issue up 👍
