### ISSUE TITLE
No authentication during installation

### ISSUE THREAD

**Issue by sebastianwachter** [kreuzerk/svg-icon-library-starter#5]
During installation of the project's dependecies I get an error stating: 

```bash
npm ERR! code E401
npm ERR! Unable to authenticate, your authentication token seems to be invalid.
npm ERR! To correct this please trying logging in again with:
npm ERR!     npm login
```

In the npm log I found that it was trying to fetch some dependency from a private repository:

```bash
3483 verbose statusCode 401
3484 verbose pkgid yaml@https://pkgs.dev.azure.com/diemobiliar/RWC/_packaging/npm-main/npm/registry/yaml/-/yaml-1.10.0.tgz
3485 verbose cwd E:\Arbeit Arbeit\svg-icon-library-starter
```

Can you maybe  make this repository public or host it on npm instead?

**Comment by nivekcode** [comment]
Yes - sorry. Thats my bad. This comes from my local npmrc config I will fix this and let you know

**Comment by nivekcode** [comment]
Sorry for the inconvenience. Everything should work fine now. Let me know if you have further questions.

**Comment by sebastianwachter** [comment]
Thanks it works now ❤️
